### ISSUE TITLE
Game returns to main menu

### ISSUE THREAD

**Issue by KroArtem** [Andrettin/Wyrmsun#118]
After some pull a new game (I've checked with random one) doesn't start and returns back to main menu with the following result in console:

```
/home/kroartem/SVN/Wyrmgus/src/stratagus/script_player.cpp:2930: CclGetPlayerData: Invalid field: CompletedQuest
error in error handling
error in error handling
```

**Comment by Andrettin** [comment]
I made a change to the scripts earlier today, but hadn't committed the concurrent change to Wyrmgus yet; this is fixed now:
https://github.com/Andrettin/Wyrmgus/commit/2beea078ebf8ac4e15447df1eb378d26577801b7

**Comment by KroArtem** [comment]
It still doesn't work. And yes, I've pulled and built new changes.

**Comment by Andrettin** [comment]
That's weird; if definitely works for me. Maybe the pulling of the new changes didn't work for some reason, because I had just committed them?

**Comment by KroArtem** [comment]
Yep, works now, sorry for disturbing.
