### ISSUE TITLE
Constructing with multiple builders needs spare resources

### ISSUE THREAD

**Issue by Szunti** [Andrettin/Wyrmsun#7]
When I start builiding with multiple builders selected, if I have just enough resources for the builiding (I guess if it's below twice the cost) only one of them starts building and I get a "Not enough resources to build ..." message for each other.

**Comment by Andrettin** [comment]
Thanks for reporting this! I fixed this issue in the latest commit (560) and added you to the "Testing" credits :)

**Comment by Szunti** [comment]
Didn't you forget to git add the source code changes, only the wyrmgus.exe is changed. And it's not fixed on my linux.

**Comment by Andrettin** [comment]
Uploading the changes to Wyrmgus as we speak :)

**Comment by Andrettin** [comment]
Done
